/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as BooksRouteRouteImport } from './routes/books/route'
import { Route as BoardGamesRouteRouteImport } from './routes/board-games/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmsStatsRouteRouteImport } from './routes/films/stats_/route'
import { Route as FilmsRootRouteRouteImport } from './routes/films/_root/route'
import { Route as FilmsIdRouteRouteImport } from './routes/films/$id/route'
import { Route as ConsoleUserRouteRouteImport } from './routes/console/user/route'
import { Route as ConsoleStudiosRouteRouteImport } from './routes/console/studios/route'
import { Route as ConsoleSessionsRouteRouteImport } from './routes/console/sessions/route'
import { Route as ConsolePeopleRouteRouteImport } from './routes/console/people/route'
import { Route as ConsoleGenresRouteRouteImport } from './routes/console/genres/route'
import { Route as ConsoleFilmsRouteRouteImport } from './routes/console/films/route'
import { Route as ConsoleCountriesRouteRouteImport } from './routes/console/countries/route'
import { Route as ConsoleCollectionsRouteRouteImport } from './routes/console/collections/route'
import { Route as ConsoleCollectionEventsRouteRouteImport } from './routes/console/collection-events/route'
import { Route as ConsoleAwardsRouteRouteImport } from './routes/console/awards/route'
import { Route as ConsoleArticlesRouteRouteImport } from './routes/console/articles/route'
import { Route as ConsoleRootIndexRouteImport } from './routes/console/_root/index'
import { Route as ConsoleFilmsIdRouteImport } from './routes/console/films_/$id'
import { Route as ConsoleAwardsIdRouteImport } from './routes/console/awards_/$id'
import { Route as ConsoleArticlesIdRouteImport } from './routes/console/articles_/$id'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRouteRoute = BooksRouteRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardGamesRouteRoute = BoardGamesRouteRouteImport.update({
  id: '/board-games',
  path: '/board-games',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsStatsRouteRoute = FilmsStatsRouteRouteImport.update({
  id: '/films/stats_',
  path: '/films/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRootRouteRoute = FilmsRootRouteRouteImport.update({
  id: '/films/_root',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIdRouteRoute = FilmsIdRouteRouteImport.update({
  id: '/films/$id',
  path: '/films/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleUserRouteRoute = ConsoleUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleStudiosRouteRoute = ConsoleStudiosRouteRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleSessionsRouteRoute = ConsoleSessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsolePeopleRouteRoute = ConsolePeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleGenresRouteRoute = ConsoleGenresRouteRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsRouteRoute = ConsoleFilmsRouteRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCountriesRouteRoute = ConsoleCountriesRouteRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCollectionsRouteRoute = ConsoleCollectionsRouteRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCollectionEventsRouteRoute =
  ConsoleCollectionEventsRouteRouteImport.update({
    id: '/collection-events',
    path: '/collection-events',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleAwardsRouteRoute = ConsoleAwardsRouteRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleArticlesRouteRoute = ConsoleArticlesRouteRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleRootIndexRoute = ConsoleRootIndexRouteImport.update({
  id: '/_root/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsIdRoute = ConsoleFilmsIdRouteImport.update({
  id: '/films_/$id',
  path: '/films/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAwardsIdRoute = ConsoleAwardsIdRouteImport.update({
  id: '/awards_/$id',
  path: '/awards/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleArticlesIdRoute = ConsoleArticlesIdRouteImport.update({
  id: '/articles_/$id',
  path: '/articles/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/board-games': typeof BoardGamesRouteRoute
  '/books': typeof BooksRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/console/articles': typeof ConsoleArticlesRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/sessions': typeof ConsoleSessionsRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/console/user': typeof ConsoleUserRouteRoute
  '/films/$id': typeof FilmsIdRouteRoute
  '/films': typeof FilmsRootRouteRoute
  '/films/stats': typeof FilmsStatsRouteRoute
  '/console/articles/$id': typeof ConsoleArticlesIdRoute
  '/console/awards/$id': typeof ConsoleAwardsIdRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console/': typeof ConsoleRootIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/board-games': typeof BoardGamesRouteRoute
  '/books': typeof BooksRouteRoute
  '/login': typeof LoginRouteRoute
  '/console/articles': typeof ConsoleArticlesRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/sessions': typeof ConsoleSessionsRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/console/user': typeof ConsoleUserRouteRoute
  '/films/$id': typeof FilmsIdRouteRoute
  '/films': typeof FilmsRootRouteRoute
  '/films/stats': typeof FilmsStatsRouteRoute
  '/console/articles/$id': typeof ConsoleArticlesIdRoute
  '/console/awards/$id': typeof ConsoleAwardsIdRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console': typeof ConsoleRootIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/board-games': typeof BoardGamesRouteRoute
  '/books': typeof BooksRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/console/articles': typeof ConsoleArticlesRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/sessions': typeof ConsoleSessionsRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/console/user': typeof ConsoleUserRouteRoute
  '/films/$id': typeof FilmsIdRouteRoute
  '/films/_root': typeof FilmsRootRouteRoute
  '/films/stats_': typeof FilmsStatsRouteRoute
  '/console/articles_/$id': typeof ConsoleArticlesIdRoute
  '/console/awards_/$id': typeof ConsoleAwardsIdRoute
  '/console/films_/$id': typeof ConsoleFilmsIdRoute
  '/console/_root/': typeof ConsoleRootIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board-games'
    | '/books'
    | '/console'
    | '/login'
    | '/console/articles'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/people'
    | '/console/sessions'
    | '/console/studios'
    | '/console/user'
    | '/films/$id'
    | '/films'
    | '/films/stats'
    | '/console/articles/$id'
    | '/console/awards/$id'
    | '/console/films/$id'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board-games'
    | '/books'
    | '/login'
    | '/console/articles'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/people'
    | '/console/sessions'
    | '/console/studios'
    | '/console/user'
    | '/films/$id'
    | '/films'
    | '/films/stats'
    | '/console/articles/$id'
    | '/console/awards/$id'
    | '/console/films/$id'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board-games'
    | '/books'
    | '/console'
    | '/login'
    | '/console/articles'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/people'
    | '/console/sessions'
    | '/console/studios'
    | '/console/user'
    | '/films/$id'
    | '/films/_root'
    | '/films/stats_'
    | '/console/articles_/$id'
    | '/console/awards_/$id'
    | '/console/films_/$id'
    | '/console/_root/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  BoardGamesRouteRoute: typeof BoardGamesRouteRoute
  BooksRouteRoute: typeof BooksRouteRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  FilmsIdRouteRoute: typeof FilmsIdRouteRoute
  FilmsRootRouteRoute: typeof FilmsRootRouteRoute
  FilmsStatsRouteRoute: typeof FilmsStatsRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-games': {
      id: '/board-games'
      path: '/board-games'
      fullPath: '/board-games'
      preLoaderRoute: typeof BoardGamesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/stats_': {
      id: '/films/stats_'
      path: '/films/stats'
      fullPath: '/films/stats'
      preLoaderRoute: typeof FilmsStatsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/_root': {
      id: '/films/_root'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$id': {
      id: '/films/$id'
      path: '/films/$id'
      fullPath: '/films/$id'
      preLoaderRoute: typeof FilmsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/user': {
      id: '/console/user'
      path: '/user'
      fullPath: '/console/user'
      preLoaderRoute: typeof ConsoleUserRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/studios': {
      id: '/console/studios'
      path: '/studios'
      fullPath: '/console/studios'
      preLoaderRoute: typeof ConsoleStudiosRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/sessions': {
      id: '/console/sessions'
      path: '/sessions'
      fullPath: '/console/sessions'
      preLoaderRoute: typeof ConsoleSessionsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/people': {
      id: '/console/people'
      path: '/people'
      fullPath: '/console/people'
      preLoaderRoute: typeof ConsolePeopleRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/genres': {
      id: '/console/genres'
      path: '/genres'
      fullPath: '/console/genres'
      preLoaderRoute: typeof ConsoleGenresRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films': {
      id: '/console/films'
      path: '/films'
      fullPath: '/console/films'
      preLoaderRoute: typeof ConsoleFilmsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/countries': {
      id: '/console/countries'
      path: '/countries'
      fullPath: '/console/countries'
      preLoaderRoute: typeof ConsoleCountriesRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/collections': {
      id: '/console/collections'
      path: '/collections'
      fullPath: '/console/collections'
      preLoaderRoute: typeof ConsoleCollectionsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/collection-events': {
      id: '/console/collection-events'
      path: '/collection-events'
      fullPath: '/console/collection-events'
      preLoaderRoute: typeof ConsoleCollectionEventsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/awards': {
      id: '/console/awards'
      path: '/awards'
      fullPath: '/console/awards'
      preLoaderRoute: typeof ConsoleAwardsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/articles': {
      id: '/console/articles'
      path: '/articles'
      fullPath: '/console/articles'
      preLoaderRoute: typeof ConsoleArticlesRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/_root/': {
      id: '/console/_root/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleRootIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films_/$id': {
      id: '/console/films_/$id'
      path: '/films/$id'
      fullPath: '/console/films/$id'
      preLoaderRoute: typeof ConsoleFilmsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/awards_/$id': {
      id: '/console/awards_/$id'
      path: '/awards/$id'
      fullPath: '/console/awards/$id'
      preLoaderRoute: typeof ConsoleAwardsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/articles_/$id': {
      id: '/console/articles_/$id'
      path: '/articles/$id'
      fullPath: '/console/articles/$id'
      preLoaderRoute: typeof ConsoleArticlesIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleArticlesRouteRoute: typeof ConsoleArticlesRouteRoute
  ConsoleAwardsRouteRoute: typeof ConsoleAwardsRouteRoute
  ConsoleCollectionEventsRouteRoute: typeof ConsoleCollectionEventsRouteRoute
  ConsoleCollectionsRouteRoute: typeof ConsoleCollectionsRouteRoute
  ConsoleCountriesRouteRoute: typeof ConsoleCountriesRouteRoute
  ConsoleFilmsRouteRoute: typeof ConsoleFilmsRouteRoute
  ConsoleGenresRouteRoute: typeof ConsoleGenresRouteRoute
  ConsolePeopleRouteRoute: typeof ConsolePeopleRouteRoute
  ConsoleSessionsRouteRoute: typeof ConsoleSessionsRouteRoute
  ConsoleStudiosRouteRoute: typeof ConsoleStudiosRouteRoute
  ConsoleUserRouteRoute: typeof ConsoleUserRouteRoute
  ConsoleArticlesIdRoute: typeof ConsoleArticlesIdRoute
  ConsoleAwardsIdRoute: typeof ConsoleAwardsIdRoute
  ConsoleFilmsIdRoute: typeof ConsoleFilmsIdRoute
  ConsoleRootIndexRoute: typeof ConsoleRootIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleArticlesRouteRoute: ConsoleArticlesRouteRoute,
  ConsoleAwardsRouteRoute: ConsoleAwardsRouteRoute,
  ConsoleCollectionEventsRouteRoute: ConsoleCollectionEventsRouteRoute,
  ConsoleCollectionsRouteRoute: ConsoleCollectionsRouteRoute,
  ConsoleCountriesRouteRoute: ConsoleCountriesRouteRoute,
  ConsoleFilmsRouteRoute: ConsoleFilmsRouteRoute,
  ConsoleGenresRouteRoute: ConsoleGenresRouteRoute,
  ConsolePeopleRouteRoute: ConsolePeopleRouteRoute,
  ConsoleSessionsRouteRoute: ConsoleSessionsRouteRoute,
  ConsoleStudiosRouteRoute: ConsoleStudiosRouteRoute,
  ConsoleUserRouteRoute: ConsoleUserRouteRoute,
  ConsoleArticlesIdRoute: ConsoleArticlesIdRoute,
  ConsoleAwardsIdRoute: ConsoleAwardsIdRoute,
  ConsoleFilmsIdRoute: ConsoleFilmsIdRoute,
  ConsoleRootIndexRoute: ConsoleRootIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  BoardGamesRouteRoute: BoardGamesRouteRoute,
  BooksRouteRoute: BooksRouteRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  FilmsIdRouteRoute: FilmsIdRouteRoute,
  FilmsRootRouteRoute: FilmsRootRouteRoute,
  FilmsStatsRouteRoute: FilmsStatsRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
